data:
    dataset: 'Colon'
    images_path: './datasets/endomapper/toy_33/'
    camera_mask_path: './datasets/endomapper/camera_mask.png'
    # apply_specular_mask_to_source_image: true  # If false, treat all pixels as non-specular (specular mask = ones)
    apply_specular_mask_to_source_image: true
    erode_camera_mask: 0
    erode_specular_mask: 0
    export_folder: 'val' # train, val
    preprocessing:
        downsize: 4 # 1, 2, 4, 8    # This is used instead of resize to only select dimensions divisible by 8
        # 1 = resize: [960, 1344]   # Original size of Endomapper images
        # 2 = resize: [480, 672]
        # 4 = resize: [240, 336]     # training size of superpoint paper
        # 8 = resize: [120, 168]

    gaussian_label: 
        enable: false # Set to false for export
        sigma: 1.

    augmentation:
        photometric:
            enable: false   # Set to false for export
    homography_adaptation:
        enable: true
        num: 50  
        aggregation: 'sum' # Just use sum
        filter_counts: 0
        valid_border_margin: 6
        homographies:
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                allow_artifacts: true
                patch_ratio: 0.85
                

training:
    workers_test: 2 # Set to 0 for debugging, 2 for production

model:
    # name: 'SuperPointNet_pretrained'        # Choose this one to load wieghts from superpoint_v1.pth
    name: 'SuperPointNet_gauss2' 
    # name:  'SuperPointNet'
    params: {
    }    
    batch_size: 1
    eval_batch_size: 1
    detection_threshold: 0.005 
    nms: 4 # 4
    top_k: 600
    subpixel:
        enable: false   

# pretrained: 'logs/old/magicpoint_synth20/checkpoints/superPointNet_200000_checkpoint.pth.tar' # 'SuperPointNet'
# pretrained: 'logs/magicpoint_synth_t2/checkpoints/superPointNet_100000_checkpoint.pth.tar'

# pretrained: pretrained/superpoint_v1.pth # MagicLeap
pretrained: "logs/old/superpoint_coco_heat2_0/checkpoints/superPointNet_gauss2_170000_checkpoint.pth.tar" # SuperpointNet_gauss2
